packages:
  - "packages/*"
  - "apps/*"
minimumReleaseAgeExclude:
  - vite@8.1.2
  - '@fallow-cli/darwin-arm64@3.0.0'
  - '@fallow-cli/darwin-x64@3.0.0'
  - '@fallow-cli/linux-arm64-gnu@3.0.0'
  - '@fallow-cli/linux-arm64-musl@3.0.0'
  - '@fallow-cli/linux-x64-gnu@3.0.0'
  - '@fallow-cli/linux-x64-musl@3.0.0'
  - '@fallow-cli/win32-arm64-msvc@3.0.0'
  - '@fallow-cli/win32-x64-msvc@3.0.0'
  - fallow@3.0.0
